### ISSUE TITLE
Unable to download video

### ISSUE THREAD

**Issue by Adrian2422** [kyonenjs/udeguchi#14]
I'm trying to download the course, the first subtitles are downloaded but an error appears with the video:

```
 node app.js -k cookie.txt https://www.udemy.com/course/writing-clean-code -q 720

 Logging with cookie

/  Getting course information    Done

 Chapter   01 Getting Started

|  Lecture   001 Welcome to the Course!

 ERROR  Failed to download the video!

  at src\download_video.js:72:20
  at ChildProcess.exithandler (child_process.js:315:5)
  at ChildProcess.emit (events.js:315:20)
  at maybeClose (internal/child_process.js:1048:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

**Comment by Cod3rMax** [comment]
me too
