### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by salytwo** [kyonenjs/udeguchi#2]
win 7

module.js:540
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\udemytest2\udeguchi\app.js:4:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

E:\udemytest2\udeguchi>

**Comment by kyonenjs** [comment]
Hello, thank you for using the tool ^^

I think you missed `Step 3` at `Require` section. You have to install `npm dependencies` by open terminal inside udeguchi folder and run command:

`npm install`

Make sure you followed all steps here : https://github.com/kyonenjs/udeguchi#require
